name: Node.js CI

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: client
        uses: actions/setup-node@v3        
      - run: npm install
          working-directory: client
      - run: npm run build --if-present
          working-directory: client
      - run: npm test
          working-directory: client